Repository nlesc-nano/CAT, pull requests merged in 2020-10, with the labels that each got.

#154 BUG: Fix an issue where indices weren't properly passed to the database
  CAT/attachment/ligand_attach.py
  CAT/attachment/ligand_opt.py
  CAT/attachment/mol_split_cm.py
  CAT/workflows/workflow.py
  CAT/workflows/workflow_dicts.py
  examples/input.py
Labels: bug

#155 ENH: Add a .yaml template for COSMO-RS LogP calculations
  CAT/data/templates/qd.yaml
Labels: enhancement

#157 Add H3O+ to the .coskf files
  CAT/__version__.py
  CAT/data/coskf/misc/Hydronium.coskf
  CAT/data/coskf/misc/__init__.py
  README.rst
  setup.py
Labels: enhancement

#158 Enable windows tests
  .github/workflows/pythonpackage.yml
Labels: Tests

#162 Improve the code-style of validating input
  CAT/data_handling/validate_input.py
Labels: Maintenance

#160 DOC: Fix the readthedocs failure
  .environment.yaml
  .readthedocs.yml
  setup.py
Labels: documentation
